server:
  port: 8000

spring:

  application:
    name: store

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:~/storedb;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:


  flyway:
    validate-on-migrate: true
    check-location: true
    enabled: true
    password:


