CREATE TABLE IF NOT EXISTS STORE (
    ID SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    ADDRESS VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS "ORDER" (
    ID SERIAL NOT NULL PRIMARY KEY,
    ADDRESS VARCHAR(255) NOT NULL,
    CONFIRMATION_DATE DATE NOT NULL,
    ORDER_STATUS VARCHAR(255) NOT NULL
);